### ISSUE TITLE
Better implementation for termux-exec?

### ISSUE THREAD

**Issue by yujincheng08** [termux-play-store/termux-issues#1]
1. Instead of `LD_PRELOAD`, we can use `seccomp` to hook `execve`, which can preserve across `fork`, `clone`, and `execve`, and is useful for static elf as we cannot `LD_PRELOAD` them.
2. For static elf, do `linker static_helper`, where the `static_helper` is a simple linker to mmap the static elf according to its elf header and then call its entry point.
3. For `/proc/self/exe`, we can use `PR_SET_MM_EXE_FILE`; in detail, unmap all `x` memories of the linker while backup their addresses, offsets, and lengths, map some anon memories to these address to occupied their place, call `PR_SET_MM_EXE_FILE`, and then mmap the linker to their old addresses with `MAP_FIXED`.

**Comment by fornwall** [comment]
Thanks, will look into it!
