### ISSUE TITLE
[Bug]: error: cannot access archive '/data/data/com.termux/cache/apt/archives/libcurl_8.9.1_aarch64.deb': No such file or directory E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (2)

### ISSUE THREAD

**Issue by REYHAN6610** [termux-play-store/termux-issues#105]
### Problem description

![1002724291](https://github.com/user-attachments/assets/f7c1223d-4cba-406d-932b-f8023a9a0c38)

I am having error while running comaind pkg example pkg upgrade pkg, install python, pkg install git. Please help me I have also used termux-change-repo

### What steps will reproduce the bug?

pkg upgrade

### What is the expected behavior?

I am having error while running comaind pkg example pkg upgrade pkg, install python, pkg install git. Please help me I have also used termux-change-repo

### System information

```shell
termux-info 0.119.0
```

**Comment by fornwall** [comment]
Hm, switching repository with `termux-change-repo` doesn't help? If not, try asking for help at one of the channels listed at: https://wiki.termux.com/wiki/Community

Closing this issue as it's not related to the play store distribution of Termux.
