### ISSUE TITLE
[Bug] I use Termux on my mobile phone redmi note 12 android version is 14,I tried to run the code "startfedora",and I got an error

### ISSUE THREAD

**Issue by Netscar** [termux-play-store/termux-issues#108]
### Problem description

![Screenshot_2024-09-05-22-35-34-283_com termux](https://github.com/user-attachments/assets/6002dd9b-601a-4b27-8abe-a0ee344b6570)

### What steps will reproduce the bug?

![Screenshot_2024-09-05-22-35-34-283_com termux](https://github.com/user-attachments/assets/1a34ab6b-f49a-4a06-b80b-e9d79feda3e3)

### What is the expected behavior?

I expect you to help me solve this error 

### System information

```shell
Termux android
```

**Comment by fornwall** [comment]
It's probably best to report this to whomever produces the `startfedora` command!
