### ISSUE TITLE
[Bug]: whatsapp

### ISSUE THREAD

**Issue by sayamanusia1** [termux-play-store/termux-issues#109]
### Problem description

$ $ chmod +x virtex.sh
No command $ found, did you mean:
 Command c in package c-script
 Command [ in package coreutils
 Command k in package kona
 Command o in package o-editor
 Command q in package q-dns-client
~ $ No command $ found, did you mean:
No command No found, did you mean:
 Command go in package golang
 Command jo in package jo
 Command o in package o-editor
 Command co in package rcs
~ $  Command c in package c-script
No command Command found, did you mean:
 Command comsatd in package mailutils
 Command common in package scala
 Command w3mman in package w3m
~ $  Command [ in package coreutils
No command Command found, did you mean:
 Command comsatd in package mailutils
 Command common in package scala
 Command w3mman in package w3m
~ $  Command k in package kona
No command Command found, did you mean:
 Command comsatd in package mailutils
 Command common in package scala
 Command w3mman in package w3m
~ $  Command o in package o-editor
No command Command found, did you mean:
 Command comsatd in package mailutils
 Command common in package scala
 Command w3mman in package w3m
~ $  Command q in package q-dns-client
No command Command found, did you mean:
 Command comsatd in package mailutils
 Command common in package scala
 Command w3mman in package w3m
~ $ termux-setup-storage $mv onemore.txt /sdcard        usage: termux-setup-storage
Use without arguments to ensure storage permission granted

### What steps will reproduce the bug?

$ $ chmod +x virtex.sh
No command $ found, did you mean:
 Command c in package c-script
 Command [ in package coreutils
 Command k in package kona
 Command o in package o-editor
 Command q in package q-dns-client
~ $ No command $ found, did you mean:
No command No found, did you mean:
 Command go in package golang
 Command jo in package jo
 Command o in package o-editor
 Command co in package rcs
~ $  Command c in package c-script
No command Command found, did you mean:
 Command comsatd in package mailutils
 Command common in package scala
 Command w3mman in package w3m
~ $  Command [ in package coreutils
No command Command found, did you mean:
 Command comsatd in package mailutils
 Command common in package scala
 Command w3mman in package w3m
~ $  Command k in package kona
No command Command found, did you mean:
 Command comsatd in package mailutils
 Command common in package scala
 Command w3mman in package w3m
~ $  Command o in package o-editor
No command Command found, did you mean:
 Command comsatd in package mailutils
 Command common in package scala
 Command w3mman in package w3m
~ $  Command q in package q-dns-client
No command Command found, did you mean:
 Command comsatd in package mailutils
 Command common in package scala
 Command w3mman in package w3m
~ $ termux-setup-storage $mv onemore.txt /sdcard        usage: termux-setup-storage
Use without arguments to ensure storage permission granted

### What is the expected behavior?

$ $ chmod +x virtex.sh
No command $ found, did you mean:
 Command c in package c-script
 Command [ in package coreutils
 Command k in package kona
 Command o in package o-editor
 Command q in package q-dns-client
~ $ No command $ found, did you mean:
No command No found, did you mean:
 Command go in package golang
 Command jo in package jo
 Command o in package o-editor
 Command co in package rcs
~ $  Command c in package c-script
No command Command found, did you mean:
 Command comsatd in package mailutils
 Command common in package scala
 Command w3mman in package w3m
~ $  Command [ in package coreutils
No command Command found, did you mean:
 Command comsatd in package mailutils
 Command common in package scala
 Command w3mman in package w3m
~ $  Command k in package kona
No command Command found, did you mean:
 Command comsatd in package mailutils
 Command common in package scala
 Command w3mman in package w3m
~ $  Command o in package o-editor
No command Command found, did you mean:
 Command comsatd in package mailutils
 Command common in package scala
 Command w3mman in package w3m
~ $  Command q in package q-dns-client
No command Command found, did you mean:
 Command comsatd in package mailutils
 Command common in package scala
 Command w3mman in package w3m
~ $ termux-setup-storage $mv onemore.txt /sdcard        usage: termux-setup-storage
Use without arguments to ensure storage permission granted

### System information

```shell
$ $ chmod +x virtex.sh
No command $ found, did you mean:
 Command c in package c-script
 Command [ in package coreutils
 Command k in package kona
 Command o in package o-editor
 Command q in package q-dns-client
~ $ No command $ found, did you mean:
No command No found, did you mean:
 Command go in package golang
 Command jo in package jo
 Command o in package o-editor
 Command co in package rcs
~ $  Command c in package c-script
No command Command found, did you mean:
 Command comsatd in package mailutils
 Command common in package scala
 Command w3mman in package w3m
~ $  Command [ in package coreutils
No command Command found, did you mean:
 Command comsatd in package mailutils
 Command common in package scala
 Command w3mman in package w3m
~ $  Command k in package kona
No command Command found, did you mean:
 Command comsatd in package mailutils
 Command common in package scala
 Command w3mman in package w3m
~ $  Command o in package o-editor
No command Command found, did you mean:
 Command comsatd in package mailutils
 Command common in package scala
 Command w3mman in package w3m
~ $  Command q in package q-dns-client
No command Command found, did you mean:
 Command comsatd in package mailutils
 Command common in package scala
 Command w3mman in package w3m
~ $ termux-setup-storage $mv onemore.txt /sdcard        usage: termux-setup-storage
Use without arguments to ensure storage permission granted
```

**Comment by fornwall** [comment]
It seems the issues here are mostly related to how to use shell and Linux - I recommend searching up a few "using the shell on Linux" tutorials, and then ask for help in https://www.reddit.com/r/linux4noobs/ and https://www.reddit.com/r/linuxquestions/, or https://www.reddit.com/r/termux/ once you know that the problem is Termux specific.
