### ISSUE TITLE
[Package]:apt upgrade

### ISSUE THREAD

**Issue by mikazajoyex231** [termux-play-store/termux-issues#121]
### Why is it worth to add this package?

pkg install wget openssl-tool proot -y && hash -r && wget https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/Installer/Ubuntu/ubuntu.sh && bash ubuntu.sh

### Home page URL

termux.com

### Source code URL

termux.com

### Packaging policy acknowledgement

- [X] The project is actively developed.
- [X] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [X] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [X] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [X] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.

**Comment by fornwall** [comment]
It's probably better to use [proot-distro](https://github.com/termux/proot-distro) here:
- `pkg install proot-distro`
- `proot-distro install ubuntu`
- `proot-distro login ubuntu`
