### ISSUE TITLE
[Bug]: gabisa install

### ISSUE THREAD

**Issue by jquin-xmanzz** [termux-play-store/termux-issues#124]
### Problem description

Tidak bisa install/apt update && ap upgrade

### What steps will reproduce the bug?

Apt update && apt upgrade

### What is the expected behavior?

Tidak ada ke eroran

### System information

```shell
Mohon beneri
```

**Comment by jquin-xmanzz** [comment]
Tolong

**Comment by jquin-xmanzz** [comment]
Tolong

**Comment by Raj420-ram** [comment]
https://bugs.termux.com

**Comment by fornwall** [comment]
Thanks! Let's track this in #30.
