### ISSUE TITLE
[Bug]: termux-change-repo not available

### ISSUE THREAD

**Issue by nirwanda3** [termux-play-store/termux-issues#130]
### Problem description

I cant acces termux-change-repo on my phone
![Screenshot_2024-09-27-07-14-50-06_84d3000e3f4017145260f7618db1d683](https://github.com/user-attachments/assets/95c260ee-8dd5-4034-a087-bf102f886e2f)

### What steps will reproduce the bug?

Termux-change-repo

### What is the expected behavior?

Termux-change-repo

### System information

```shell
Termux-change-repo
```

**Comment by fornwall** [comment]
`termux-change-repo` is not yet available in Termux on Google Play - it uses a package repository with modifications to be able to run under the updated `targetSdk` that Google Play requires, which so far has no mirrors.

Why do you need to use a mirror? One known reason is https://github.com/termux-play-store/termux-issues/issues/30, cloudflare being blocked in Indonesia.
