### ISSUE TITLE
[Bug]: ifconfig

### ISSUE THREAD

**Issue by Ankulchaudhary** [termux-play-store/termux-issues#132]
### Problem description

![Screenshot_20240928_091608](https://github.com/user-attachments/assets/8623ae90-10eb-4127-8665-c54e34f45410)

### What steps will reproduce the bug?

![Screenshot_20240928_091608](https://github.com/user-attachments/assets/ba7f7372-32cf-4b7f-a2fc-08d2be5caca1)

### What is the expected behavior?

![Uploading Screenshot_20240928_091608.jpg…]()

### System information

```shell
Ifconfig
```

**Comment by fornwall** [comment]
Try installing pkg in net-tools and try again (after running hash -r in the existing terminal session, if necessary).
