### ISSUE TITLE
[Bug]: cannot use all command that have install, upgrade, update

### ISSUE THREAD

**Issue by Valen-sudo** [termux-play-store/termux-issues#135]
### Problem description

Using all commanda that have install, upgradd, update

### What steps will reproduce the bug?

Using all commanda that have install, upgradd, update

### What is the expected behavior?

I think the server

### System information

```shell
Failed to fetch https://termux.net/dists/stable/InRelease  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown. The name in the certificate does not match the expected.  Could not handshake: Error in the certificate verification. [IP: 36.86.63.185 443]
```

**Comment by fornwall** [comment]
Hi! Which country are you in?

**Comment by Valen-sudo** [comment]
I'm in Indonesia

Pada Min, 29 Sep 2024 19.28, Fredrik Fornwall ***@***.***>
menulis:

**Comment by fornwall** [comment]
Thanks! Let's close this issue in favour of #30.
