### ISSUE TITLE
Failed to connected the Termux's server

### ISSUE THREAD

**Issue by CrixzDreamerID** [termux-play-store/termux-issues#138]
### Problem description

When I wanted to run the PKG upgrade program on Termux for the first time, a notification appeared that the server was not connected.Even though cellular data is active and the internet is still there
![Screenshot_20241001-100625](https://github.com/user-attachments/assets/b6556ad7-bb74-4f0a-81fa-417f11c0cf1a)

### What steps will reproduce the bug?

.

### What is the expected behavior?

.

### System information

```shell
.
```

**Comment by fornwall** [comment]
Thanks for reporting! You're in Indonesia? See https://github.com/termux-play-store/termux-issues/issues/30, and please try out what's proposed in https://github.com/termux-play-store/termux-issues/issues/30#issuecomment-2381344274 and see if that works (please write in that issue, to gather info in one place)!
