### ISSUE TITLE
Not login termax 

### ISSUE THREAD

**Issue by King4797** [termux-play-store/termux-issues#143]
I have login to GitHub account but not login to the termax
![Screenshot_2024-10-05-22-35-49-04_84d3000e3f4017145260f7618db1d683](https://github.com/user-attachments/assets/1603d6e7-98df-4804-ba0e-1c22e1eef845)

**Comment by King4797** [comment]
Please logout my in termax

**Comment by fornwall** [comment]
Doesn't seem to be a Termux specific issue - try to seek help in some forum, perhaps where you are getting a script you're trying to run or similar.
