### ISSUE TITLE
[Package]: update

### ISSUE THREAD

**Issue by FajarApr** [termux-play-store/termux-issues#145]
### Why is it worth to add this package?

~ $ pkg install update
Ign:1 https://termux.net stable InRelease
Ign:1 https://termux.net stable InRelease
Ign:1 https://termux.net stable InRelease
Err:1 https://termux.net stable InRelease
  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown. The name in the certificate does not match the expected.  Could not handshake: Error in the certificate verification. [IP: 36.86.63.185 443]
All packages are up to date.
Warning: Failed to fetch https://termux.net/dists/stable/InRelease  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown. The name in the certificate does not match the expected.  Could not handshake: Error in the certificate verification. [IP: 36.86.63.185 443]
Warning: Some index files failed to download. They have been ignored, or old ones used instead.
Error: Unable to locate package update

### Home page URL

Ign:1 https://termux.net stable InRelease Ign:1 https://termux.net stable InRelease Ign:1 https://termux.net stable InRelease Err:1 https://termux.net stable InRelease

### Source code URL

https://github.com/termux-play-store/termux-issues/issues/new?assignees=&labels=package+request&projects=&template=02-package-request.yml&title=%5BPackage%5D%3A+

### Packaging policy acknowledgement

- [X] The project is actively developed.
- [X] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [X] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [X] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [X] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.

**Comment by fornwall** [comment]
See #30, and specifically if trying what [this comment](https://github.com/termux-play-store/termux-issues/issues/30#issuecomment-2211390169) shows helps?
