### ISSUE TITLE
[Bug]: termux-change-repo not available

### ISSUE THREAD

**Issue by Karibo86** [termux-play-store/termux-issues#146]
### Problem description

Change Repo not found

### What steps will reproduce the bug?

![Uploading Screenshot_20241006_184215_Termux.jpg…]()

### System information

```shell
Report issues at https://bugs.termux.com
~ $ termux-change-repo
termux-change-repo: command not found
```

**Comment by fornwall** [comment]
`termux-change-repo` is not yet available in Termux on Google Play - it uses a package repository with modifications to be able to run under the updated `targetSdk` that Google Play requires, which so far has no mirrors.

Why do you need to use a mirror? One known reason is https://github.com/termux-play-store/termux-issues/issues/30, cloudflare being blocked in Indonesia.
