### ISSUE TITLE
Termux-package

### ISSUE THREAD

**Issue by adblock25** [termux-play-store/termux-issues#163]
### Why is it worth to add this package?

{
  "pkg_format": "debian",
  "packages": {
    "name": "termux-main",
    "distribution": "stable",
    "component": "main",
    "url": "https://packages-cf.termux.dev/apt/termux-main"
  },
  "root-packages": {
    "name": "termux-root",
    "distribution": "root",
    "component": "stable",
    "url": "https://packages-cf.termux.dev/apt/termux-root"
  },
  "x11-packages": {
    "name": "termux-x11",
    "distribution": "x11",
    "component": "main",
    "url": "https://packages-cf.termux.dev/apt/termux-x11"
  }
}

### Home page URL

https://github.com/adblock25

### Source code URL

https://github.com/termux/termux-app.git

### Packaging policy acknowledgement

- [X] The project is actively developed.
- [X] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [X] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [X] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [X] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.

**Comment by adblock25** [comment]
https://github.com/termux/termux-packages.wiki.git

**Comment by Thakor772** [comment]
git@github.com:termux-play-store/termux-issues.git
