### ISSUE TITLE
Is this a problem with wiki or this version of termux?

### ISSUE THREAD

**Issue by a404050aaa** [termux-play-store/termux-issues#179]
### Discussed in https://github.com/termux-play-store/termux-issues/discussions/131

<div type='discussions-op-text'>

<sup>Originally posted by **Djspac3** September 28, 2024</sup>
I noticed that the config file for termux is under ~/.config/termux but the wiki says ~/.termux/
is that like just not updated wiki or something I have to figure out?</div>

**Comment by fornwall** [comment]
As noted in that discussions both locations work (the F-Droid build will be updated to support both as well, during a transition period).
