### ISSUE TITLE
[Bug]: Files not displayed in list

### ISSUE THREAD

**Issue by MikieAC** [termux-play-store/termux-issues#18]
### Problem description

Only directories are shown in the LS command. Files are not displayed.

Also, the following script refuses to return any files:

#show selection 
for f in *; do
echo "Item -> $f" 
done

### What steps will reproduce the bug?

Perform the LS command in any directory that contains files. The files will not be displayed.

### What is the expected behavior?

Files should be shown

### System information

```shell
.../0/Download $ termux-info
Termux Variables:
TERMUX_EXEC__PROC_SELF_EXE=/data/data/com.termux/files/usr/bin/termux-info
TERMUX_VERSION=0.129
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.net stable main
Updatable packages:
All packages up to date
termux-tools version:
3.0.7
Android version:
13
Kernel build information:
Linux localhost 4.19.113-27223811 #1 SMP PREEMPT Tue May 28 13:43:06 KST 2024 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-G781V
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
.../0/Download $
```

**Comment by MikieAC** [comment]
There are 250 .jpg files in this directory, but none of them show up

![Screenshot_20240624_100754_Termux](https://github.com/termux-play-store/termux-issues/assets/173698674/97450a18-14be-4ae5-ad24-9c02dd6b2bc4)

**Comment by fornwall** [comment]
Hi! Can you try running `termux-setup-storage` once more, give Termux the `All files access` in the resulting dialog and try again?

If that doesn't make the `.jpg` files show up, does `ls` show a simple file? As in, what is the output of running the below?

```sh
touch ~/new-file
ls ~/
```

**Comment by MikieAC** [comment]
Turns out, you can't do it from inside Termux... You have to select:

**_Settings > Apps_**

Then click the hamburger and select: 

**_Special Access_**

![Screenshot_20240624_141426_Settings](https://github.com/termux-play-store/termux-issues/assets/173698674/8aab743b-9c0d-43a2-8e07-b6e6ac7632b2)

And then select:

**_All file access_**

![Screenshot_20240624_141209_Settings](https://github.com/termux-play-store/termux-issues/assets/173698674/122072be-e467-4852-aec2-d1bb5927fb8f)


And then turn the slider ON for Termux (the slider is OFF after installation)

**Comment by MikieAC** [comment]
Closed
