### ISSUE TITLE
[Package]: instagram password 

### ISSUE THREAD

**Issue by Subhammali** [termux-play-store/termux-issues#186]
### Why is it worth to add this package?

Instagram password 

### Home page URL

+91 80007 54558

### Source code URL

+91 80007 54558

### Packaging policy acknowledgement

- [X] The project is actively developed.
- [X] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [X] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [X] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [X] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.

**Comment by Subhammali** [comment]
Password change

**Comment by Subhammali** [comment]
Password

**Comment by Subhammali** [comment]
Pass

**Comment by wlydaladrysy** [comment]
Termux Variables:
TERMUX_EXEC__PROC_SELF_EXE=/data/data/com.termux/files/usr/bin/termux-info
TERMUX_VERSION=googleplay.2024.10.30
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.net stable main
Updatable packages:
command-not-found/stable 2.4.0-55 aarch64 [upgradable from: 2.4.0-48]
curl/stable 8.11.1 aarch64 [upgradable from: 8.10.1-2]
debianutils/stable 5.21 aarch64 [upgradable from: 5.20]
inetutils/stable 2.5 aarch64 [upgradable from: 2.4-2]
less/stable 668 aarch64 [upgradable from: 661]
libc++/stable 27c aarch64 [upgradable from: 27b]
libcurl/stable 8.11.1 aarch64 [upgradable from: 8.10.1-2]
libnghttp3/stable 1.7.0 aarch64 [upgradable from: 1.6.0]
libsmartcols/stable 2.40.2-2 aarch64 [upgradable from: 2.40.2-1]
nano/stable 8.3 aarch64 [upgradable from: 8.2]
util-linux/stable 2.40.2-2 aarch64 [upgradable from: 2.40.2-1]
termux-tools version:
3.0.8
Android version:
15
Kernel build information:
Linux localhost 6.1.84-android14-11-g5c500deec3a7-ab12418271 #1 SMP PREEMPT Thu Sep 26 10:25:24 UTC 2024 aarch64 Android
Device manufacturer:
Google
Device model:
Pixel 9 Pro
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
