### ISSUE TITLE
[Bug]: bell won't disable

### ISSUE THREAD

**Issue by batinthestacks** [termux-play-store/termux-issues#22]
### Problem description

The terminal bell won't disable after following the wiki instructions.

### What steps will reproduce the bug?

Set option in both config files just in case

- file mentioned in wiki
~ $ grep bell .termux/termux.properties
bell-character=ignore
- file existing in install
~ $ grep bell .config/termux/termux.properties
bell-character=ignore

Hit tab tab (command completion)

Hear bell instead of nothing or vibration

### What is the expected behavior?

There should be no bell sound

### System information

```shell
Termux Variables:
TERMUX_EXEC__PROC_SELF_EXE=/data/data/com.termux/files/usr/bin/termux-info
TERMUX_VERSION=0.129
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.net stable main
Updatable packages:
All packages up to date
termux-tools version:
3.0.7
Android version:
14
Kernel build information:
Linux localhost 6.1.25-android14-11-28243294-abS928USQS2AXE4 #1 SMP PREEMPT Tue May 28 02:31:42 UTC 2024 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-S928U1
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by fornwall** [comment]
Thanks for reporting :bow: ! This has been fixed in the `googleplay.2024.06.27` version, which has just been released and should be available as an update on Google Play shortly.
