### ISSUE TITLE
Not make dir[Bug]: 

### ISSUE THREAD

**Issue by Arun2717** [termux-play-store/termux-issues#23]
### Problem description

My termux not make dir so plz help and 

### What steps will reproduce the bug?

mkdir termux
File only read

### What is the expected behavior?

😐😐

### System information

```shell
mkdir
```

**Comment by Arun2717** [comment]
Please help me

**Comment by nhockey** [comment]
![Screenshot_20240702-172523](https://github.com/termux-play-store/termux-issues/assets/436149/fdc4e141-a04b-4d28-89f8-5b52ac4c5671)
Seems fine?  If you need different permissions on the folder use chmod on it (folders always have to be executable to be used mind you!) you can add that with go+x
