### ISSUE TITLE
[Bug]: After update to 1.129, `<Ctrl>-<alt>-#` now covers the bottom half of the window with a box that just has "#" (such as "2"), for several seconds after each tab switch

### ISSUE THREAD

**Issue by SwuduSusuwu** [termux-play-store/termux-issues#27]
### Problem description

If you use tabs, this makes it almost impossible to use Termux,
because the huge box (which just has the number "#" -- such as **2**) covers the bottom half of the window (the most important spot where you input text) for several seconds whenever you switch tabs.

### What steps will reproduce the bug?

Launch Termux
Press `<Ctrl>+c` to spawn new tabs
Press `<Ctrl>+#` to switch to tab **#**
![Termux ctrl-alt-2](https://github.com/termux-play-store/termux-issues/assets/168943815/df18aeb4-bd94-4863-a961-0aed310993b2)

### What is the expected behavior?

Just as the old (_Fdroid_) Termux, new (_Google Store_) Termux should show a small box with the number **#**.

### System information

```shell
~/SubStack $ termux-info
Termux Variables:
TERMUX_EXEC__PROC_SELF_EXE=/data/data/com.termux/files/usr/bin/termux-info
TERMUX_VERSION=0.129
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.net stable main
Updatable packages:
All packages up to date
termux-tools version:
3.0.7
Android version:
14
Device manufacturer:
Google
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
~/SubStack $
```
```

**Comment by SwuduSusuwu** [comment]
How to have this small -- as the _Fdroid_'s Termux was -- or move it to the top of the window? If it was at the top, it would not cover the text input.
If must revert to old _Fdroid_ build of Termux, how to preserve what Termux has, so do not have to backup+restore all that Termux has?

**Comment by fornwall** [comment]
@SwuduSusuwu This should be fixed in the latest `googleplay.2024.06.27` app update that's out on Google Play, which restores the old less annoying small notification toast - let me know if it works as expected!

**Comment by SwuduSusuwu** [comment]
> @SwuduSusuwu This should be fixed in the latest `googleplay.2024.06.27` app update that's out on Google Play, which restores the old less annoying small notification toast - let me know if it works as expected!

Success
![Screenshot_20240701-024518](https://github.com/termux-play-store/termux-issues/assets/168943815/367229c2-f5a7-4fab-b9f4-ab4e9fced3ac)

**Comment by fornwall** [comment]
Thanks for reporting and following up!
