### ISSUE TITLE
[Bug]: https://bugs.termux.com

### ISSUE THREAD

**Issue by Rajveer9106291760** [termux-play-store/termux-issues#28]
### Problem description

https://bugs.termux.com

### What steps will reproduce the bug?

Docs:       https://doc.termux.com
Community:  https://social.termux.com

Working with packages:
 - Search:  pkg search <query>
 - Install: pkg install <package>
 - Upgrade: pkg upgrade

Report issues at https://bugs.termux.com
![Screenshot_20240702_123442](https://github.com/termux-play-store/termux-issues/assets/174418532/7dd8eed9-7f6e-442f-81e2-df5dfb91a41f)

### What is the expected behavior?

Bug

### System information

```shell
Bug
```

**Comment by nhockey** [comment]
Um, could you elaborate? Your bug just seems to be the ability to report bugs?
