### ISSUE TITLE
Iconv lacking cp437 and ISO-8859-1

### ISSUE THREAD

**Issue by nhockey** [termux-play-store/termux-issues#32]
### Problem description

Older programs that predated utf-8 and relied on iconv commonly expected it to have both/either cp437 and/or ISO-8859-1. 
![Screenshot_20240703-173722](https://github.com/termux-play-store/termux-issues/assets/436149/6be46936-ca46-45d5-8690-e4c4b35ed573)

### What steps will reproduce the bug?

Compile an application which didn't initially have utf-8 support and relies on iconv. 

### What is the expected behavior?

iconv to be more complete 

### System information

```shell
Termux Variables:
TERMUX_EXEC__PROC_SELF_EXE=/data/data/com.termux/files/usr/bin/termux-info                      TERMUX_VERSION=googleplay.2024.06.27
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.net stable main
Updatable packages:
cmake/stable 3.30.0 aarch64 [upgradable from: 3.29.6]
openssh-sftp-server/stable 9.8p1-3 aarch64 [upgradable from: 9.8p1-2]
openssh/stable 9.8p1-3 aarch64 [upgradable from: 9.8p1-2]
termux-tools version:
3.0.7
Android version:
14
Kernel build information:
Linux localhost 5.10.198-android13-4-00047-g7a2aa337ab82-ab11664978 #1 SMP PREEMPT Wed Apr 3 07:17:30 UTC 2024 aarch64 Android
Device manufacturer:
Google
Device model:
Pixel 7 Pro
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```
This did work in the non-playstore version.

(Though annoyingly crypt.h doesn't work right either, but I just disable that in epic5 🤷)

**Comment by nhockey** [comment]
Interestingly enough it looks like the extra encodings are supposed to be enabled. 🤔

https://github.com/termux-play-store/termux-packages/blob/main/packages%2Flibiconv%2Fbuild.sh

**Comment by fornwall** [comment]
Thanks for looking into this!

I think this should be fixed by https://github.com/termux-play-store/termux-packages/commit/8e8d2b7c2bdab62616192cec184edd16e1dec1a8. The problem was that iconv.h was provided by the `ndk-sysroot` package, which uses the iconv functionality built into the Android libc (which lacks many encodings).

If you run `pkg up` you should be updated to new `ndk-sysroot` and `libiconv` packages, so that `libiconv` provides `iconv.h`. After rerunning configure and make epic5 should work.

> (Though annoyingly crypt.h doesn't work right either, but I just disable that in epic5 🤷)

That should be fixable by installing the `libcrypt` package, and add a `#include <crypt.h>` to `source/functions.c`.

**Comment by nhockey** [comment]
Thanks for looking into this!
> 
> I think this should be fixed by https://github.com/termux-play-store/termux-packages/commit/8e8d2b7c2bdab62616192cec184edd16e1dec1a8. The problem was that iconv.h was provided by the `ndk-sysroot` package, which uses the iconv functionality built into the Android libc (which lacks many encodings).
> If you run `pkg up` you should be updated to new `ndk-sysroot` and `libiconv` packages, so that `libiconv` provides `iconv.h`. After rerunning configure and make epic5 should work.

Worked like a charm!

> > (Though annoyingly crypt.h doesn't work right either, but I just disable that in epic5 🤷)
> 
> That should be fixable by installing the `libcrypt` package, and add a `#include <crypt.h>` to `source/functions.c`.

You are an absolute legend! I simply added a section to the defs.h.in file that he uses and worked perfectly. 

Patch time coming up!

Thanks again!
