### ISSUE TITLE
[Bug]: Can't update through Google Play 

### ISSUE THREAD

**Issue by dsghub** [termux-play-store/termux-issues#34]
### Problem description

Google Play shows a new version, but updates fail with an unspecific error messag that suggests go try later.

### What steps will reproduce the bug?

1. Open Google Play on an Android device that has Termux 0.101 installed.
2. Navigate to the part of Google Play that offers updates for individual apps
3. Initiate the update for Termux to 2024.06.27
4. Some 24 MByte are dowloaded
5. Error message "Can't install Termux - Try again"

### What is the expected behavior?

Expected behaviour at step 5 is that the update is installes

### System information

```shell
This happens on various versions of Android, such as Android 14 on a Pixel 7, or the current Android container on a Chromebook.
```

**Comment by fornwall** [comment]
Thanks for reporting!

To update from version `0.101`, you need to backup files you want to keep (like copying from `$HOME` to `/sdcard`, or transfer files off the device) and then uninstall the app (which will wipe all files under `$PREFIX`) before installing again to receive the update.

That is a one-time thing only, future updates does not require this.
