### ISSUE TITLE
[Bug]: can't install qemu

### ISSUE THREAD

**Issue by HarryL0L** [termux-play-store/termux-issues#36]
### Problem description

5/7/2024: Tried to install qemu-system-x86-64
in termux(Google play store)
Can't install qemu
Everything is fine for termux fdroid build

### What steps will reproduce the bug?

1.pkg upgrade

2.pkg install x11-repo

3.pkg install qemu-system-x86-64

### What is the expected behavior?

![Screenshot_2024-07-05-13-38-16-55_84d3000e3f4017145260f7618db1d683](https://github.com/termux-play-store/termux-issues/assets/88073458/a19b8b10-8029-4745-9059-9e4939e0d2c6)

### System information

```shell
Termux version : googleplay.2024.06.27
Android version : 13
```

**Comment by fornwall** [comment]
Hi! If you run `pkg` update you should now be able to install qemu.

Unfortunately it's quite likely to not work running qemu without adapting it to the changes necessary for Google Play distribution (updated targetSdk/termux-exec), but please share any problems you run into.

**Comment by HarryL0L** [comment]
Okay 
For now I'll stick with fdroid Termux
