### ISSUE TITLE
[Bug]: Can't update, upgrade, and install

### ISSUE THREAD

**Issue by rhamid-r3** [termux-play-store/termux-issues#39]
### Problem description

i can't update, upgrade, and install

### What steps will reproduce the bug?

![Screenshot_2024-07-11-22-49-28-533_com termux](https://github.com/termux-play-store/termux-issues/assets/175328782/c8f5e44e-63f0-4af2-b1d0-bb3c6f644451)

### What is the expected behavior?

successfully do everything

### System information

```shell
$pkg update && pkg upgrade
$pkg install php
```

**Comment by fornwall** [comment]
See #30.
