### ISSUE TITLE
[Bug]: wget, curl doesn't working 

### ISSUE THREAD

**Issue by unexp-int** [termux-play-store/termux-issues#45]
### Problem description

im trying to download file from github when using wget give me error : (Segmentation fault)

when using curl -O giving me after some seconds : (couldn't connect to server)

i don't know the problem from packages or from application itself.

### What steps will reproduce the bug?

installing something from internet.

### System information

```shell
Termux Variables:
TERMUX_EXEC__PROC_SELF_EXE=/data/data/com.termux/files/usr/bin/termux-info
TERMUX_VERSION=googleplay.2024.07.07
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.net stable main
Updatable packages:
All packages up to date
termux-tools version:
3.0.7
Android version:
11
Kernel build information:
Linux localhost 4.19.127-g036eaa1450cd-dirty #1 SMP PREEMPT Tue Dec 13 22:22:44 CST 2022 aarch64 Android
Device manufacturer:
INFINIX MOBILITY LIMITED
Device model:
Infinix X688B
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by fornwall** [comment]
> im trying to download file from github when using wget give me error : (Segmentation fault)
> when using curl -O giving me after some seconds : (couldn't connect to server)

Is this problem (wget segfaulting and curl unable to connect) in general for many urls, or specific to one problematic url?

If it's only one URL and it's not sensitive / personal, could you share the problematic URL?
