### ISSUE TITLE
[Bug]: termux-change-repo is not available

### ISSUE THREAD

**Issue by ysfona** [termux-play-store/termux-issues#46]
### Problem description

With Termux, "termux-change-repo" doesn't work with my new Android phone.
![received_1206660647189058](https://github.com/user-attachments/assets/c7c1b1a1-9c6a-4e1c-aeea-26eda31f9ba8)
![received_1625724791617144](https://github.com/user-attachments/assets/3bd05f26-ebd8-423d-942e-8a82c0245363)

### What steps will reproduce the bug?

Just opening Termux app.

### What is the expected behavior?

Install Mikhmon app in my phone.

### System information

```shell
Command not found.
```

**Comment by fornwall** [comment]
`termux-change-repo` is not yet available in Termux on Google Play - it uses a package repository with modifications to be able to run under the updated `targetSdk` that Google Play requires, which so far has no mirrors.

Why do you need to use a mirror? One known reason is https://github.com/termux-play-store/termux-issues/issues/30, cloudflare being blocked in Indonesia.
