### ISSUE TITLE
[Package]: bitcoin

### ISSUE THREAD

**Issue by Graysonbarton** [termux-play-store/termux-issues#52]
### Why is it worth to add this package?

Add the ability to make changes to mining rewards and mining complexity.
Also adds the ability to expand the blockchain beyond the current 21,000,000 capp ( this should only be done with a supermajority approval vote from community).

### Source code URL

Http://www.bitcoin.org

### Packaging policy acknowledgement

- [X] The project is actively developed.
- [X] #365
- [X] #364
- [X] #363

- [x] #362
- [X] #361
- [X] #360

### Additional information

No

**Comment by fornwall** [comment]
A bitcoin package already exists - install with `pkg install bitcoin`.

**Comment by mghol10929-dotcom** [comment]
****
