### ISSUE TITLE
[Bug]: .txt , .so  file is not show 

### ISSUE THREAD

**Issue by godzillavss** [termux-play-store/termux-issues#57]
### Problem description

.txt , .so  file is not show for ls for any folder any location only showing directories (folder) for my 4 device same problem 😔
![Screenshot_2024_0726_034050](https://github.com/user-attachments/assets/34f66808-0ad2-4dc5-bd30-a0ae3a41b6f5)
![Screenshot_2024_0726_034104](https://github.com/user-attachments/assets/aac92619-1dd2-4c98-b839-f8d8bdc41cb1)

### What steps will reproduce the bug?

By first step 

### What is the expected behavior?

.txt , .so  file is not show for ls for any folder any location only showing directories (folder) for my 4 device same problem 😔

### System information

```shell
.txt , .so  file is not show for ls for any folder any location only showing directories (folder) for my 4 device same problem 😔
```

**Comment by godzillavss** [comment]
Can you solve this problem fast 😳

**Comment by fornwall** [comment]
Be sure to run the latest version available, and run `termux-setup-storage` - this problem has been resolved for quite some time.
