### ISSUE TITLE
[Bug]: Spam Y

### ISSUE THREAD

**Issue by AknownGuy** [termux-play-store/termux-issues#6]
### Problem description

It just bugs out and spams y in the text output till you close it in like notifications 

### What steps will reproduce the bug?

After loading in, type "yes" and it should work

### What is the expected behavior?

Without the bug it should just say like no command found or suggest commands that it thinks you meant to type

With the bug it just spams the letter y

### System information

```shell
Termux Variables:
unsupported
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.net stable main
Updatable packages:
debianutils/stable 5.19 aarch64 [upgradable from: 5.18]
termux-tools/stable 3.0.6 all [upgradable from: 3.0.4]
termux-tools version:
3.0.4
Android version:
11
Kernel build information:
Linux localhost 4.19.127-g7642ade87-dirty #1 SMP PREEMPT Wed May 18 21:37:51 CST 2022 aarch64 Android
Device manufacturer:
Blackview
Device model:
A55
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by fornwall** [comment]
See https://man7.org/linux/man-pages/man1/yes.1.html for information about the `yes` program:

> yes - output a string repeatedly until killed
