### ISSUE TITLE
[Bug]: strpXpubg menu

### ISSUE THREAD

**Issue by MohamedAyman-meludas** [termux-play-store/termux-issues#60]
### Problem description

Cant open the menu

### What steps will reproduce the bug?

Idk

### System information

```shell
Termux Variables:
TERMUX_EXEC__PROC_SELF_EXE=/data/data/com.termux/files/usr/bin/termux-info
TERMUX_VERSION=googleplay.2024.07.07
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.net stable main
Updatable packages:
apt/stable 2.9.6 aarch64 [upgradable from: 2.9.4-2]
ca-certificates/stable 2024.07.02 all [upgradable from: 2024.03.11-2]
command-not-found/stable 2.4.0-35 aarch64 [upgradable from: 2.4.0-30]
curl/stable 8.9.0 aarch64 [upgradable from: 8.8.0]
debianutils/stable 5.20 aarch64 [upgradable from: 5.19]
less/stable 661 aarch64 [upgradable from: 633-1]
libcurl/stable 8.9.0 aarch64 [upgradable from: 8.8.0]
openssl/stable 3.3.1 aarch64 [upgradable from: 3.2.1-1]
termux-exec/stable 1.4 aarch64 [upgradable from: 1.3]
termux-tools version:
3.0.7
Android version:
14
Kernel build information:
Linux localhost 4.14.336-g6117cca349ee #1 SMP PREEMPT Sat Jul 13 00:10:32 EEST 2024 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi Note 9S
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by nhockey** [comment]
Are you talking about the slide out menu on the left side of the terminal? If so, it can be a bit tricky if/when you use gestures to navigate your phone. I use gestures on my phone and have found that if I touch and hold near the edge the drawer kind of peeks out, then I can move my finger to the right sliding it out the rest of the way.  So basically don't try to drag the menu out immediately, the operating system will interpret that as a back action, if you hesitate momentarily it will allow you to slide it out without interpreting it as that back action; just wait for it to peak out first.

But, if you're talking about the tap and hold menu; I don't have anything for you, that works fine here.
