### ISSUE TITLE
[Bug]: If you input the word yes Termux types out a bunch of Ys and you have to reset the app to stop it

### ISSUE THREAD

**Issue by Hyperspeed77000** [termux-play-store/termux-issues#63]
### Problem description

I was just playing around with Termux and typed in yes and it what I said in the title

### What steps will reproduce the bug?

Typing yes

### What is the expected behavior?

Don't type a bunch of Ys

### System information

```shell
~$ yes
```

**Comment by fornwall** [comment]
This is intended behaviour - see https://www.gnu.org/software/coreutils/manual/html_node/yes-invocation.html.

Use `ctrl+c` to abort a running program.
