### ISSUE TITLE
[Bug]: I want my Instagram account back was hacked by someone 

### ISSUE THREAD

**Issue by Kartik1305856** [termux-play-store/termux-issues#66]
### Problem description

I want my Instagram account back was hacked by someone 
![Screenshot_2024-06-26-08-44-10-43_1c337646f29875672b5a61192b9010f9](https://github.com/user-attachments/assets/8afa65ec-3239-4189-8cb0-c8fb2d59f2c7)

### What steps will reproduce the bug?

I want this account access
![Screenshot_2024-06-26-08-44-10-43_1c337646f29875672b5a61192b9010f9](https://github.com/user-attachments/assets/7671bc8a-7524-462e-9d42-453cbacedde4)

### What is the expected behavior?

I expected that this my help me as soon as possible 

### System information

```shell
My my account access to my device
```

**Comment by fornwall** [comment]
Sorry, not something Termux can help with.
