### ISSUE TITLE
𔑀Bounty Hunter

### ISSUE THREAD

**Issue by Kaiposhka** [termux-play-store/termux-issues#70]
### Why is it worth to add this package?

𔑀𝙷ⷡ𝚄ⷪ𝙽ͧ𝚃ꙵ𝙴ⷮ𝚁ꙷ

𝙹𝙰𝚁𝙰𝙽𝙶 𝚃𝙴𝚁𝙻𝙸𝙷𝙰𝚃 𝚂𝙴𝙻𝙰𝙻𝚄 𝚃𝙴𝚁𝙻𝙸𝙱𝙰𝚃

𝐁𝐔𝐓𝐔𝐇 𝐃𝐀𝐍𝐀 𝐂𝐄𝐏𝐀𝐓💰

### Home page URL

Http.//bountyhunter.com

### Source code URL

Http.//bountyhunter.com

### Packaging policy acknowledgement

- [X] The project is actively developed.
- [X] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [X] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [X] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [X] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.

**Comment by fornwall** [comment]
Sorry, not suitable as a Termux package.
