### ISSUE TITLE
[Bug]:bug termux Google play  with openjdk 

### ISSUE THREAD

**Issue by juandimarcano** [termux-play-store/termux-issues#85]
### Problem description

I receive a friendly greeting my thermos app since I learned that received the update for Android 11 does not run open jdk packages or kotlin packages when I try to test springboot in my termux or koolin app gives the following error , the error is 
Failed to load native library:jansi-2.4.0-cdd02d61aab01e90-libjansi.so. osinfo: Linux/arm64
java.lang.UnsatisfiedLinkError: /data/data/com.termux/files/usr/tmp/jansi-2.4.0-cdd02d61aab01e90-libjansi.so: dlopen failed: library "libc.so.6" not found: needed by /data/data/com.termux/files/usr/tmp/jansi-2.4.0-cdd02d61aab01e90-libjansi.so in namespace (default)

### What steps will reproduce the bug?

$pkg install openjdk 
$pkg install kotlin 
then the next steps create a kotlin file and compile it to Java with openjdk
The error is :
Failed to load native library:jansi-2.4.0-cdd02d61aab01e90-libjansi.so. osinfo: Linux/arm64
java.lang.UnsatisfiedLinkError: /data/data/com.termux/files/usr/tmp/jansi-2.4.0-cdd02d61aab01e90-libjansi.so: dlopen failed: library "libc.so.6" not found: needed by /data/data/com.termux/files/usr/tmp/jansi-2.4.0-cdd02d61aab01e90-libjansi.so in namespace (default)

### What is the expected behavior?

please hope they can fix the app error ,termux is a great app greetings from Venezuela

### System information

```shell
Termux Variables:
TERMUX_EXEC__PROC_SELF_EXE=/data/data/com.termux/files/usr/bin/termux-info
TERMUX_VERSION=googleplay.2024.07.07
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.net stable main
# root-repo (sources.list.d/root.list)
deb https://root-packages.termux.net/ root main
Updatable packages:
c-ares/stable 1.33.1 aarch64 [upgradable from: 1.33.0]
command-not-found/stable 2.4.0-38 aarch64 [upgradable from: 2.4.0-37]
composer/stable 2.7.8 all [upgradable from: 2.7.7]
coreutils/stable 9.5-1 aarch64 [upgradable from: 9.5]
gh/stable 2.55.0 aarch64 [upgradable from: 2.54.0]
libdevmapper/root 2.03.26 aarch64 [upgradable from: 2.03.25]
libluajit/stable 2.1.1724232689 aarch64 [upgradable from: 2.1.1720049189]
libmsgpack/stable 6.1.0 aarch64 [upgradable from: 6.0.2]
libnghttp3/stable 1.5.0 aarch64 [upgradable from: 1.4.0]
nano/stable 8.1 aarch64 [upgradable from: 8.0]
pinentry/stable 1.3.1 aarch64 [upgradable from: 1.3.0-1]
termux-tools version:
3.0.7
Android version:
12
Kernel build information:
Linux localhost 5.4.254-android12-9-660867-g3a346a240055-ab560 #1 SMP PREEMPT Wed Jul 17 18:32:38 CST 2024 aarch64 Android
Device manufacturer:
TECNO
Device model:
TECNO KI5k
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by juandimarcano** [comment]
Heyy help

**Comment by fornwall** [comment]
@Jota0108 Thanks for reporting the issue!

Could you try updating to latest version of all packages (run `pkg up`) and see if that fixes the issue for you?
