### ISSUE TITLE
[Bug]: can't change repository 

### ISSUE THREAD

**Issue by Pixel383** [termux-play-store/termux-issues#87]
### Problem description

termux-change-repo invalid command

### What steps will reproduce the bug?

~ $ termux-change-repo
termux-change-repo: command not found

### What is the expected behavior?

Should allow me to enable multiple repositories for file information.

I believe this jeopardized install of kali Linux. 

### System information

```shell
~ $ termux-change-repo
termux-change-repo: command not found
```

**Comment by Pixel383** [comment]
Running android 14 on Pixel 7, 2024 up to date. Just downloaded termux today from official download site, so is latest version.

**Comment by fornwall** [comment]
See #46.
