### ISSUE TITLE
[Bug]: Cannot access file on /sdcard

### ISSUE THREAD

**Issue by hanyman7** [termux-play-store/termux-issues#9]
### Problem description

I can see and r/w files on subdirs of /sdcard, however, not of /sdcard itself.
Directories are visible - but not files

### What steps will reproduce the bug?

Uninstall Fdroid termux and install Play store version. Now I can't see files on /sdcard. I can, however, see directories and files in subdirectories.
I did give the app access to all media files.

### What is the expected behavior?

Fdroid allows r/w of files on root of /sdcard

### System information

```shell
Termux Variables: TERMUX_APP_PACKAGE_MANAGER=apt TERMUX_EXEC__PROC_SELF_EXE=/data/data/com.termux/files/usr/bin/termux-info TERMUX_VERSION=0.127 TERMUX__USER_ID=0 Packages CPU architecture: aarch64 Subscribed repositories: # sources.list deb https://termux.net stable main Updatable packages: All packages up to date termux-tools version: 3.0.6 Android version: 14 Kernel build information: Linux localhost 5.15.123-android13-3-28579584 #1 SMP PREEMPT Tue May 7 18:11:49 KST 2024 aarch64 Android Device manufacturer: samsung Device model: SM-A546U LD Variables: LD_LIBRARY_PATH= LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by fornwall** [comment]
Thanks for reporting - please subscribe to https://github.com/termux-play-store/termux-apps/issues/18 for updates regarding this!
