### ISSUE TITLE
[Bug]: Cannot restore from a F-Droid install of Termux

### ISSUE THREAD

**Issue by DanielNewtonNoesges** [termux-play-store/termux-issues#90]
### Problem description

/data/data/com.termux/files/usr/bin/login: 40: exec: /data/data/com.termux/files/usr/bin/bash: Permission denied

[Process completed (code 126) - press Enter]

### What steps will reproduce the bug?

Copying my termux

### What is the expected behavior?

Locked termux

### System information

```shell
/data/data/com.termux/files/usr/bin/login: 40: exec: /data/data/com.termux/files/usr/bin/bash: Permission denied

[Process completed (code 126) - press Enter]
```

**Comment by fornwall** [comment]
Restoring from a Termux installation from F-Droid onto a Termux installation from Google Play (or vice versa) does unfortunately not yet work, due to the necessary changes not being in place in the F-Droid packages. Will be resolved in the future, but for now that is just a current limitation.
